// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qbllfnlxknpncujqatlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFibGxmbmx4a25wbmN1anFhdGxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NjYxMDgsImV4cCI6MjA2NzQ0MjEwOH0.63NulGlSBUVaLd6DJNe1tNLW1rqhkG-xoMSyv5feRsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);